New monitoring script and other stuff

diff --git a/dotfiles/bash_profile b/dotfiles/bash_profile
--- a/dotfiles/bash_profile
+++ b/dotfiles/bash_profile
@@ -1,4 +1,4 @@
-export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
+export PATH="$PATH:/opt/local/bin:/opt/local/sbin"
 export PATH=$PATH:/usr/local/sbin
 export PATH=$PATH:~/bin
 
@@ -10,9 +10,7 @@ export PATH=$PATH:~/Library/Python/3.7/bin
 
 alias pdflatex="/Library/TeX/Root/bin/x86_64-darwin/pdflatex"
 alias ls="ls -hal"
-
-export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
-[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
+alias ios="open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app"
 
 export GITAWAREPROMPT=~/.bash/git-aware-prompt
 source "${GITAWAREPROMPT}/main.sh"
@@ -23,6 +21,9 @@ export HISTCONTROL=ignoreboth
 export HISTSIZE=10000
 export HISTFILESIZE=10000
 export ERL_AFLAGS="-kernel shell_history enabled"
+
+export PLUG_EDITOR='x-mine://open?file=__FILE__&line=__LINE__'
+export ECTO_EDITOR='rubymine'
 
 rubymine() {
   RUBYMINE="/Applications/RubyMine.app/Contents/MacOS/rubymine"
@@ -82,6 +83,19 @@ exercism-download-and-test() {
   mix test --include pending;
 }
 
+announce() {
+  "$@"
+  ret=$?
+  if [[ $ret -eq 0 ]]
+  then
+    echo "Command finished: '$@'" | say -f -
+  else
+    echo "Command failed: '$@'" | say -f -
+  fi
+
+  return $ret
+}
+
 if [ -f ~/.bash_profile_priv ]; then
   source ~/.bash_profile_priv
 fi
@@ -89,3 +103,5 @@ fi
 . $HOME/.asdf/asdf.sh
 
 . $HOME/.asdf/completions/asdf.bash
+
+alias crowdin3='java -jar /usr/local/bin/crowdin-cli.jar'
